# Generated by Django 3.2.5 on 2021-08-01 06:07

from django.db import migrations


def apply_migration(apps, schema_editor):
    Group = apps.get_model("auth", "group")
    Group.objects.get_or_create(name="Managers")
    Group.objects.get_or_create(name="Sellers")
    Group.objects.get_or_create(name="Supporters")


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            apply_migration, reverse_code=migrations.RunPython.noop
        ),
    ]
